// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $analysis from "./routes/analysis.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $chat from "./routes/chat.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $stats from "./routes/stats.tsx";
import * as $vault from "./routes/vault.tsx";
import * as $Chat from "./islands/Chat.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import * as $DisorderAnalysis from "./islands/DisorderAnalysis.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $Profile from "./islands/Profile.tsx";
import * as $Stats from "./islands/Stats.tsx";
import * as $Vault from "./islands/Vault.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/analysis.tsx": $analysis,
    "./routes/api/joke.ts": $api_joke,
    "./routes/chat.tsx": $chat,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/profile.tsx": $profile,
    "./routes/stats.tsx": $stats,
    "./routes/vault.tsx": $vault,
  },
  islands: {
    "./islands/Chat.tsx": $Chat,
    "./islands/Dashboard.tsx": $Dashboard,
    "./islands/DisorderAnalysis.tsx": $DisorderAnalysis,
    "./islands/Login.tsx": $Login,
    "./islands/Profile.tsx": $Profile,
    "./islands/Stats.tsx": $Stats,
    "./islands/Vault.tsx": $Vault,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
